/* Generated by scripts/generate-voice.ts. Do not edit. */
import type { StoryTiming } from "./story";

export const VOICE_TIMING: StoryTiming | null = {
  duration: 33.205,
  sentences: [
    {
      start: 0,
      end: 4.609,
      words: [
        {
          word: "your",
          start: 0,
        },
        {
          word: "best",
          start: 0.522,
        },
        {
          word: "work",
          start: 0.871,
        },
        {
          word: "lives",
          start: 1.219,
        },
        {
          word: "in",
          start: 1.614,
        },
        {
          word: "a",
          start: 1.753,
        },
        {
          word: "terminal",
          start: 1.834,
        },
        {
          word: "but",
          start: 2.67,
        },
        {
          word: "you",
          start: 2.844,
        },
        {
          word: "can't",
          start: 2.972,
        },
        {
          word: "always",
          start: 3.239,
        },
        {
          word: "stay",
          start: 3.576,
        },
        {
          word: "at",
          start: 3.843,
        },
        {
          word: "your",
          start: 3.947,
        },
        {
          word: "desk",
          start: 4.11,
        },
      ],
    },
    {
      start: 5.166,
      end: 8.649,
      words: [
        {
          word: "one",
          start: 5.166,
        },
        {
          word: "command",
          start: 5.457,
        },
        {
          word: "and",
          start: 6.002,
        },
        {
          word: "that",
          start: 6.281,
        },
        {
          word: "same",
          start: 6.536,
        },
        {
          word: "terminal",
          start: 6.803,
        },
        {
          word: "is",
          start: 7.279,
        },
        {
          word: "right",
          start: 7.454,
        },
        {
          word: "there",
          start: 7.663,
        },
        {
          word: "on",
          start: 7.895,
        },
        {
          word: "your",
          start: 8.011,
        },
        {
          word: "phone",
          start: 8.162,
        },
      ],
    },
    {
      start: 9.311,
      end: 13.723,
      words: [
        {
          word: "it",
          start: 9.311,
        },
        {
          word: "connects",
          start: 9.543,
        },
        {
          word: "directly",
          start: 9.985,
        },
        {
          word: "when",
          start: 10.553,
        },
        {
          word: "it",
          start: 10.739,
        },
        {
          word: "can",
          start: 10.844,
        },
        {
          word: "and",
          start: 11.343,
        },
        {
          word: "through",
          start: 11.598,
        },
        {
          word: "an",
          start: 11.923,
        },
        {
          word: "encrypted",
          start: 12.028,
        },
        {
          word: "relay",
          start: 12.55,
        },
        {
          word: "when",
          start: 12.899,
        },
        {
          word: "it",
          start: 13.073,
        },
        {
          word: "can't",
          start: 13.177,
        },
      ],
    },
    {
      start: 14.292,
      end: 17.392,
      words: [
        {
          word: "invite",
          start: 14.292,
        },
        {
          word: "someone",
          start: 14.664,
        },
        {
          word: "to",
          start: 14.942,
        },
        {
          word: "watch",
          start: 15.047,
        },
        {
          word: "they",
          start: 15.743,
        },
        {
          word: "only",
          start: 15.976,
        },
        {
          word: "type",
          start: 16.254,
        },
        {
          word: "if",
          start: 16.568,
        },
        {
          word: "you",
          start: 16.661,
        },
        {
          word: "let",
          start: 16.8,
        },
        {
          word: "them",
          start: 16.986,
        },
      ],
    },
    {
      start: 18.077,
      end: 20.898,
      words: [
        {
          word: "and",
          start: 18.077,
        },
        {
          word: "when",
          start: 18.286,
        },
        {
          word: "claude",
          start: 18.495,
        },
        {
          word: "needs",
          start: 18.809,
        },
        {
          word: "an",
          start: 19.041,
        },
        {
          word: "answer",
          start: 19.145,
        },
        {
          word: "your",
          start: 19.702,
        },
        {
          word: "phone",
          start: 19.935,
        },
        {
          word: "tells",
          start: 20.202,
        },
        {
          word: "you",
          start: 20.504,
        },
      ],
    },
    {
      start: 21.641,
      end: 26.181,
      words: [
        {
          word: "one",
          start: 21.641,
        },
        {
          word: "keystroke",
          start: 21.92,
        },
        {
          word: "ends",
          start: 22.535,
        },
        {
          word: "it",
          start: 22.884,
        },
        {
          word: "nothing",
          start: 23.557,
        },
        {
          word: "leaves",
          start: 24.021,
        },
        {
          word: "your",
          start: 24.346,
        },
        {
          word: "machine",
          start: 24.532,
        },
        {
          word: "until",
          start: 25.043,
        },
        {
          word: "you",
          start: 25.357,
        },
        {
          word: "say",
          start: 25.507,
        },
        {
          word: "so",
          start: 25.74,
        },
      ],
    },
    {
      start: 27.017,
      end: 31.231,
      words: [
        {
          word: "it",
          start: 27.017,
        },
        {
          word: "works",
          start: 27.203,
        },
        {
          word: "with",
          start: 27.493,
        },
        {
          word: "the",
          start: 27.655,
        },
        {
          word: "tools",
          start: 27.771,
        },
        {
          word: "you",
          start: 28.108,
        },
        {
          word: "already",
          start: 28.282,
        },
        {
          word: "use",
          start: 28.747,
        },
        {
          word: "and",
          start: 29.455,
        },
        {
          word: "never",
          start: 29.664,
        },
        {
          word: "touches",
          start: 29.942,
        },
        {
          word: "your",
          start: 30.256,
        },
        {
          word: "shell",
          start: 30.407,
        },
        {
          word: "config",
          start: 30.639,
        },
      ],
    },
    {
      start: 32.427,
      end: 33.205,
      words: [
        {
          word: "wrapper",
          start: 32.427,
        },
      ],
    },
  ],
};
