/* Records the narration as one take with ElevenLabs and saves sentence and word timings.
 * Run: bun run voice
 *
 * Needs ELEVENLABS_API_KEY (apps/video/.env.local). Optional: ELEVENLABS_VOICE_ID,
 * ELEVENLABS_MODEL_ID. The take is cached by text + voice + settings.
 */
import { createHash } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { STORY, storyText, type SentenceTiming, type StoryTiming } from "../src/story";

const API_KEY = process.env.ELEVENLABS_API_KEY;
/* "Sarah": a warm, confident, natural female narrator from the ElevenLabs default library. */
const VOICE_ID = process.env.ELEVENLABS_VOICE_ID ?? "EXAVITQu4vr4xnSDxMaL";
const MODEL_ID = process.env.ELEVENLABS_MODEL_ID ?? "eleven_multilingual_v2";
const VOICE_SETTINGS = {
  stability: 0.45,
  similarity_boost: 0.8,
  style: 0.25,
  use_speaker_boost: true,
  speed: 0.97,
};

const ROOT = join(import.meta.dir, "..");
const VOICE_DIR = join(ROOT, "public/audio/voice");
const CACHE_DIR = join(VOICE_DIR, "cache");
const MANIFEST = join(ROOT, "src/voice.generated.ts");

type Alignment = {
  characters: string[];
  character_start_times_seconds: number[];
  character_end_times_seconds: number[];
};
type Take = { audio_base64: string; alignment: Alignment };

if (!API_KEY) {
  console.error("ELEVENLABS_API_KEY is not set. Add it to apps/video/.env.local and run again.");
  process.exit(1);
}
mkdirSync(CACHE_DIR, { recursive: true });

const request = {
  text: storyText(),
  model_id: MODEL_ID,
  voice_settings: VOICE_SETTINGS,
};
const key = createHash("sha256")
  .update(JSON.stringify({ VOICE_ID, request }))
  .digest("hex")
  .slice(0, 12);
const cached = join(CACHE_DIR, `story-${key}.json`);

let take: Take;
if (existsSync(cached)) {
  take = JSON.parse(readFileSync(cached, "utf8")) as Take;
  console.log("cached   story take");
} else {
  const response = await fetch(
    `https://api.elevenlabs.io/v1/text-to-speech/${VOICE_ID}/with-timestamps?output_format=mp3_44100_128`,
    {
      method: "POST",
      headers: { "xi-api-key": API_KEY, "content-type": "application/json" },
      body: JSON.stringify(request),
    },
  );
  if (!response.ok) throw new Error(`ElevenLabs ${response.status}: ${await response.text()}`);
  take = (await response.json()) as Take;
  writeFileSync(cached, JSON.stringify(take));
  console.log("voiced   story take");
}

const mp3 = join(CACHE_DIR, `story-${key}.mp3`);
writeFileSync(mp3, Buffer.from(take.audio_base64, "base64"));
copyFileSync(mp3, join(VOICE_DIR, "story.mp3"));

/* Find each sentence in the aligned characters, then the start of every word inside it. */
const {
  characters,
  character_start_times_seconds: starts,
  character_end_times_seconds: ends,
} = take.alignment;
const spoken = characters.join("");
let cursor = 0;
const sentences: SentenceTiming[] = STORY.map(({ text }) => {
  const index = spoken.indexOf(text, cursor);
  if (index < 0) throw new Error(`Could not align "${text}"`);
  cursor = index + text.length;
  const words: SentenceTiming["words"] = [];
  const pattern = /[A-Za-z']+/g;
  for (const match of text.matchAll(pattern)) {
    words.push({ word: match[0].toLowerCase(), start: starts[index + (match.index ?? 0)] ?? 0 });
  }
  return {
    start: starts[index] ?? 0,
    end: ends[index + text.length - 1] ?? 0,
    words,
  };
});
const duration = Math.max(...ends);

const timing: StoryTiming = { duration: Number(duration.toFixed(3)), sentences };
writeFileSync(
  MANIFEST,
  `/* Generated by scripts/generate-voice.ts. Do not edit. */\nimport type { StoryTiming } from "./story";\n\nexport const VOICE_TIMING: StoryTiming | null = ${JSON.stringify(timing, null, 2)};\n`,
);

sentences.forEach((s, i) => {
  console.log(`  ${s.start.toFixed(2)}–${s.end.toFixed(2)}s  ${STORY[i]?.text}`);
});
console.log(`\nstory.mp3 · ${duration.toFixed(2)}s · voice ${VOICE_ID} · ${MODEL_ID}`);
